name: CI

on: [pull_request]

jobs:
  clientCi:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #      - uses: actions/cache@v2.1.1
      #        with:
      #          path: "./node_modules/*"
      #          key: package.json

      # NPM Install TODO: Implement Cache
      - name: YARN Install
        run: yarn install --frozen-lockfile

      - name: Build client
        run: yarn build

      - name: Run tests
        run: yarn test

#      - name: Run linter
#        run: yarn lint
#        working-directory: ./client
